apiVersion: apps/v1
kind: Deployment
metadata:
  name: student2-deployment
spec:
  selector:
    matchLabels:
      app: student2
  template:
    metadata:
      labels:
        app: student2
    spec:
      containers:
      - name: student2
        image: registry.tanzu.dk/ops2devops/student2:v1
